# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Pylogmon.pot
PackageVersion: 2.7.5
InstallerLocale: zh-CN
InstallerType: nullsoft
Scope: machine
InstallModes:
- silentWithProgress
UpgradeBehavior: install
Protocols:
- '0'
- '3'
- GPL
FileExtensions:
- exe
ReleaseDate: 2024-02-13
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/pot-app/pot-desktop/releases/download/2.7.5/pot_2.7.5_x86-setup.exe
  InstallerSha256: 7F25A1C52A40677239A09960026652CF6E8AB2A836778A69B9C4D5B4A33056A7
- Architecture: x64
  InstallerUrl: https://github.com/pot-app/pot-desktop/releases/download/2.7.5/pot_2.7.5_x64-setup.exe
  InstallerSha256: B6C8557A65598FF95BB3EB0FD2F65700D61947A814FCD3E92050D9D7DEFF1EE8
- Architecture: arm64
  InstallerUrl: https://github.com/pot-app/pot-desktop/releases/download/2.7.5/pot_2.7.5_arm64-setup.exe
  InstallerSha256: DDE3B2D003AE7B9995BD47A5B85B512B61CE612724C60CAB4DA5F57DAE7E6DDC
ManifestType: installer
ManifestVersion: 1.5.0
